### ISSUE TITLE
Add command to undo fetch and checkout

### ISSUE THREAD

**Issue by shoelzer** [github/git-lfs#1189]
Git LFS provides control over which files to fetch/cache (`lfs.fetchinclude`, `lfs.fetchexclude`) and which files to put in the working dir (`checkout <filespec>`). But once files are in the cache or working dir there is no (easy) way to undo those operations. I would like a command to change files into placeholders in the working dir and delete cached files.

The goal of this command is to free disk space used by LFS files. It goes much further than `prune`. I should be able to remove all LFS files from the working dir and cache. By default, the command should protect against data loss by verifying that files exist on the LFS server before deleting, but there should also be an option to skip that check.

I don't know if this should be a new command, multiple new commands, or options added to existing commands. Some ideas...

* Single new command: `scrub`, `clear`, `free`
* Multiple new commands: `uncheckout` and `unfetch`
* New options for commands: `checkout --placeholder` and `fetch --clear-cache`

**Comment by technoweenie** [comment]
I think this sounds like a great idea. I think `git lfs prune` could get some kind of `--all` option that just basically does `rm -rf .git/lfs/objects`. "Uncheckout" (the act of replacing LFS tracked files in the working directory with the LFS pointer) should probably be a new command though. I don't like the idea of a command like `git lfs checkout` doing the opposite given a new flag like `git lfs checkout --clear`.

**Comment by sinbad** [comment]
Thanks for raising this, it's a solid point. 

In terms of deleting fetched content in the `.git/lfs/objects` store, I think that's a valid extension to `git lfs prune` of anything that would have been omitted at fetch time because of `lfs.fetchinclude` and `lfs.fetchexclude`. That could be default behaviour, the rest of `prune` is just an inverse of `fetch` with a little date padding to avoid thrashing.

As for resetting what's currently in the working copy back to pointers, you can actually achieve this now using `git reset --hard` *if* the object isn't already fetched into `.git/lfs/objects`. The smudge filter will get invoked and *if* the object data isn't local already and the fetch is suppressed due to include/exclude settings then it will write the pointer to the working copy instead, over the top of any current content. The only reason this doesn't work as a solution right now is that you have no real way to easily remove all the objects you've already fetched that now match those settings, which the changes above for `prune` would do.

So I think this doesn't need any extra commands, just an enhancement to the default behaviour of `git lfs prune`.

**Comment by technoweenie** [comment]
FWIW, an "uncheckout" command was requested in https://github.com/github/git-lfs/issues/944#issuecomment-175418615 too. I think I'd prefer having our own documented/tested command, instead of encouraging `git reset --hard` with caveats that the user has to worry about.

**Comment by shoelzer** [comment]
Thanks for the tips on `git reset --hard`. I can use that right now.

I like the idea of extending `git lfs prune` and adding "uncheckout". Perhaps `git lfs checkin`?

**Comment by sinbad** [comment]
I'd favour something like `git lfs checkout --clean` since it's not really doing the opposite of what `checkout` normally does, it's just doing it again from scratch with the latest settings.

**Comment by swordfly** [comment]
Hi All, recently I'm evaluating LFS support big binary test data. I'm really like the idea to revert local checkout LFS file to pointer file. Is it available now in latest LFS version? Because we have many large test data, each one is around 2GB, so we want to revert all  LFS files to pointer files even if those are latest version. Thanks!

**Comment by farleylai** [comment]
I think people start to ask for more from Git LFS to serve large files on demand such as Google Drive File Stream or Dropbox smart sync despite limited local storage.
Before that, a clumsy way to manually convert the large file back is to use `git lfs clean` as follows:
```
$> mv largefile.bin largefile.bin.bak
$> cat largefile.bin.bak | git lfs clean > largefile.bin
$> rm largefile.bin.bak
```
Those lines can be wrapped as a script command. 
Unfortunately, the clean filter needs to compute based on the entire file and is running slow.
Any suggestion to improve the performance would be highly anticipated.

**Comment by ttaylorr** [comment]
@farleylai Without more serious workarounds, I think that this is the "best" solution for now. That said, I really like the idea of an `git-lfs-stash` command. "stash" is perhaps confusing as it has other connotations, but something that would remove un-checkout the object and potentially prune it from your local cache.

This is a reasonably sized project, but I would be more than happy to guide you or anyone else through it as an OSS contribution. That said, if nobody takes this on, I'd be happy to add it myself within the next few releases (cc @technoweenie).

**Comment by farleylai** [comment]
@ttaylorr I just figured out a way to check out the pointer file as is without re-computation by untracking the file type temporarily:
```
git lfs untrack '*.bin'
git checkout largefile.bin
git lfs track '*.bin'
```
However, I still imagine a handy flag works as follows:
When the flag is set true, the pointer files are always checked out as is with git checkout/fetch/pull. The user must explicitly download the large files with git lfs pull. The recovery is simply to check out again.
Otherwise, git-lfs always materializes the pointers implicitly with with git checkout/fetch/pull.
This essentially means to control the filtering by tracking add/push and untracking checkout/pull.
So far, the closest one is set by running git lfs install --skip-smudge but only works for the first time clone.
A little bit more flexibility would be appreciated.

**Comment by ttaylorr** [comment]
> However, I still imagine a handy flag works as follows:

If I'm understanding your proposal correctly, I think that this is largely accomplishable with the `--include` and `--exclude` flags that are provided in Git LFS. If what you're looking for are ways to _by default_ not check an LFS object out into the working tree, I think that this should be left to scripting within the repository.

**Comment by technoweenie** [comment]
> If what you're looking for are ways to by default not check an LFS object out into the working tree, I think that this should be left to scripting within the repository.

You can do this by running:

```sh
# in your working directory
$ git config --file=.lfsconfig lfs.fetchexclude "*"
```

Add that `.lfsconfig` file to your repository, and the default exclude value will be used if no alternate is given (user git config, arguments to `git lfs clone` or `git lfs pull`, etc).

**Comment by farleylai** [comment]
@ttaylorr Not exactly. I am aligned with the OP. So the requirement is for git to checkout/recover the pointer files as is in the repo if unchanged or absent in a transparent way. Sure enough, specifying --exlude or lfs.fetchexclude can serve as the hint but git-lfs does not recover the pointer files essentially.

**Comment by ttaylorr** [comment]
@farleylai Sorry, can you explain what you mean by the phrase "recover the pointer file(s)"? Thanks.

**Comment by technoweenie** [comment]
I think he means the reverse of `smudge`. It sounds like he has a repository with the pointer files already replaced by the actual large files via the smudge filter, and wants to reclaim a little local disk space by removing them.

You can script it, or do it manually right now:

```sh
# all LFS files are real
$ git lfs ls-files
9252a75c94 * bin/again.bin
0263829989 * bin/b.bin
98ea6e4f21 * bin/hi.bin
b9f86fab47 * gif/atom-undo.gif
d1c8fab514 * gif/droidtocat.gif
d1c8fab514 * gif/dupe.gif
55d51edb30 * png/render.png

$ git config lfs.fetchexclude '*'
$ git show HEAD:bin/again.bin > bin/again.bin
$ git lfs pull # no-op because of lfs.fetchexclude

# bin/again.bin is just a pointer
$ git lfs ls-files
9252a75c94 - bin/again.bin
0263829989 * bin/b.bin
98ea6e4f21 * bin/hi.bin
b9f86fab47 * gif/atom-undo.gif
d1c8fab514 * gif/droidtocat.gif
d1c8fab514 * gif/dupe.gif
55d51edb30 * png/render.png
```

That's pretty cumbersome, and doesn't remove the file from `.git/lfs/objects`.

**Comment by farleylai** [comment]
```
...
$ git show HEAD:bin/again.bin > bin/again.bin
...
```
is exactly the key command to getting the pointer file back but it seems to require the path matching what is listed by `git lfs ls-files`. Alternatively, turning off the lfs tracking temporarily and `git checkout` works as shown earlier in general for files and directories relative to cwd. Ultimately, removing the corresponding lfs files in `.git/lfs/objects` accordingly is welcome. So the followup question is how to get the lfs object path in .git/lfs/objects corresponding to the oid sha256. Is it sufficient to just delete it?

**Comment by technoweenie** [comment]
Yes, LFS will happily re-download the files if they're not in `.git/lfs/objects`.

**Comment by hannwong** [comment]
@technoweenie Any effort started on this? Not that I need this urgently; I have a script that users run to empty the entire `.git/lfs/objects` folder and restore every pointer into the working directory. I even have a script for `git lfs pull origin <some-large-file>`.

This feature isn't urgent because non-tech users don't have huge files (Word documents less than 5MB). Tech users who need to flit between huge files (ISOs, binaries, etc) can already revert huge files to text pointers on their own.

**Comment by ttaylorr** [comment]
@hannwong no, but this is something that I think would be worth considering for the forthcoming v2.5.0 release.

**Comment by zzhang2019** [comment]
Looking for this feature as well and google lead me to this thread, do we it supported ready?

**Comment by ttaylorr** [comment]
> do we it supported ready?

Not yet, but we will make sure to update this issue if/when we do.

**Comment by fstefanov** [comment]
I use this one from my git root:
```
lfs_files=($(git lfs ls-files -n))
for file in "${lfs_files[@]}"; do
  git cat-file -e "HEAD:${file}" && git cat-file -p "HEAD:${file}" > "$file"
done
```
@rokroskar you can always do
```
rm -rf .git/lfs/objects
git add -u
```
After loop is over, this will give you clean tree
```
git status
Not currently on any branch.
nothing to commit, working tree clean
```

**Comment by rokroskar** [comment]
@fstefanov this will write back the pointer but not delete the cached objects in `.git/lfs/objects` which still use up disk space. It also makes git think that the file has changed, at least with my version of git (2.21.0).

**Comment by cardoso-neto** [comment]
>no, but this is something that I think would be worth considering for the forthcoming v2.5.0 release.

We're past 2.7 already and we're still using scripts we hacked together to accomplish this.
Any way you guys could devise your own git-lfs certified and approved command for the next release?

My team :heart: git-lfs's ease of use and it'd be great to have these pruning features out-of-the-box.

**Comment by 8ctopus** [comment]
Great feature, I look forward to it being implemented. Here's the cleanup script I use in the meanwhile based on @fstefanov 
#!/bin/bash
lfs_files=($(git lfs ls-files -n))
for file in "${lfs_files[@]}"; do
  git cat-file -e "HEAD:${file}" && git cat-file -p "HEAD:${file}" > "$file"
done
rm -rf .git/lfs/objects

**Comment by gregwym** [comment]
For only undo checkout, I find the following to be faster and easier. 

```
git lfs uninstall
git lfs ls-files -n | xargs rm
git resotre .
git lfs install
```

**Comment by hobofan** [comment]
Here is a small program that I've written and been using for a few weeks: https://github.com/hobofan/lfs-unload

Still not a builtin solution, but it's been pretty robust for me so far.

**Comment by skullthug** [comment]
Well it's been 4 years and this ability seems, from a new-comer perspective, like something that would be assumed to be core functionality and not requiring weird script fiddling. Any idea if this is on a road map somewhere at least?

**Comment by bk2204** [comment]
It is not on a roadmap anywhere, but we'll of course happily accept a suitable patch.  if you want to remove unused LFS objects, that can be done easily with `git lfs prune`.  If you just want to do a checkout of your branch without the LFS files, you can do that with `GIT_LFS_SKIP_SMUDGE=1 git read-tree -u --reset HEAD`.  Note that that will delete all changes to your working tree.

**Comment by skullthug** [comment]
I'm afraid contributing is beyond my know-how, but I'd urge you look at @hobofan 's solution at least and see if that's something approachable.
Unfortunately after spending a full week debugging this, I can safely say git lfs prune does **nothing** in my case, when trying to turn LFS files back into pointers, if they already exist locally. The only thing that has technically worked is scripting @technoweenie 's [comment](https://github.com/git-lfs/git-lfs/issues/1189#issuecomment-349019951). But, in my situation it results in a [mess to cleanup](https://stackoverflow.com/questions/11383094/unstaged-changes-left-after-git-reset-hard/41041863#41041863) with the working tree afterwards, on a level that I would never recommend this casually to a team-member.

My case specifically is I want to apply a lfs fetchexclude (on a folder where we store our binary builds), and unload the LFS files mentioned in the exclude- ideally without having to reset the entire working tree but at this point I would consider that a small mercy. 
Note: If I apply the fetchexclude **before** fetching LFS on a new clone, it works as expected as the files are generated as pointers. But again, if you don't remember todo this and the LFS files are pulled, they're really hard to get rid of. I also don't want to have to re-clone my repository in the future if we ever add more folders to exclude. So a built-in LFS unload/clean operation here would be overwhelmingly welcomed.

(GIT_LFS_SKIP_SMUDGE=1 is the one thing I haven't tried yet, so I'll edit this comment with the results.)

**Comment by Pierre-Bartet** [comment]
I would happily help if I had the required knowledge. Also I doubt it would be so easy, otherwise such a core issue would not have survived 4 years. It looks full of annoying corner cases.
As anyone tried @farleylai solution on the long term ?

```console
$ git lfs untrack '*.bin'
$ git checkout largefile.bin
$ git lfs track '*.bin'
```

**Comment by DoctorObvious** [comment]
I just wanted to pile on that this is an important use case. As someone transitioning from git-annex (where optional downloads are part of the workflow), I really need the ability to get some files always and others sometimes. The fetchexclude does fine with this. However, I need to be able to free up space and ditch the optional files (golden outputs for testing) at times.

A "drop" or "prune option for 'optional'" type of approach would greatly improve the usefulness of this tool.

**Comment by ncoghlan** [comment]
Similar to @skullthug, I also tried  `GIT_LFS_SKIP_SMUDGE=1 git read-tree -u --reset HEAD` and found it did nothing at all on its own - the checked out binary remained the checked out binary, instead of reverting back to the placeholder file as desired.

The combination that worked was:

    $ git show HEAD:bin/example.bin > bin/example.bin # Revert the contents to match the placeholder file
    $ GIT_LFS_SKIP_SMUDGE=1 git read-tree -u --reset HEAD # Fix the working tree state to be unmodified

For my use case, I prefer to keep the file downloaded, as the point is just to switch the working tree between actual binaries and placeholder files depending on what I'm doing, so something like a `git lfs checkout-placeholder bin/example.bin` command that reverted to the state that exists between `git lfs fetch` and `git lfs checkout bin/example.bin` would be desirable.

**Comment by baterflyrity** [comment]
Is there any progress for `uncheckout` command? I cant wait it on Windows platform!

**Comment by bk2204** [comment]
I believe my statement from above still applies:

> It is not on a roadmap anywhere, but we'll of course happily accept a suitable patch.

We're a small team and we're working on other things at the moment.

**Comment by baterflyrity** [comment]
> 
> 
> I believe my statement from above still applies:
> 
> > It is not on a roadmap anywhere, but we'll of course happily accept a suitable patch.
> 
> We're a small team and we're working on other things at the moment.

What a pitty! So Ive wrote my own alternative of git-lfs and moved to it instead of patching 5.5 years old issue.

**Comment by rpgoldman** [comment]
I'm having this problem right now, and it's proving resistant to the above work-arounds:

1. Trying to reset to a state before change to LFS-tracked files:

 ```
 $ git reset --hard
Updating files: 100% (2/2), done.
HEAD is now at c5a64f4 Update responses.
Encountered 2 file(s) that should have been pointers, but weren't:
	figures/side_scatter_saturation_positive_controls.pdf
	replication-paper.pdf
   ```
2. But these two files are *not* listed as git-lfs managed:
  ```
   $ git lfs ls-files | grep replication-paper.pdf
(base) rpg@rpg-macbook-pro: ~/papers/2021-yeast-gates-papers $ git lfs ls-files | grep figures/side_scatter_saturation_positive_controls.pdf
(base) rpg@rpg-macbook-pro: ~/papers/2021-yeast-gates-papers $
  ```

  Hence, when I try to `git show` these files, I just get back the full file contents instead of the file hash.

3. When I look at a git diff, though, it sure looks like git lfs is managing things:
  ```
$ git diff main -- replication-paper.pdf
diff --git a/replication-paper.pdf b/replication-paper.pdf
index 4797d03..b781d43 100644
--- a/replication-paper.pdf
+++ b/replication-paper.pdf
@@ -1,3 +1,3 @@
 version https://git-lfs.github.com/spec/v1
-oid sha256:3fedee39903f7c6353f0e1601f4600e22f93fe6ad94e3afa35cf390c25079ae1
-size 2270857
+oid sha256:024be9892158c2012a8ad553c655050fc68a695df99f525a86d81a9f0ad83b68
+size 2471327
  ```
There is a lot of discussion in this issue thread about removing a file from `.git/lfs/objects`, but no recipe is given for *finding* the entry in there that corresponds to the file we are trying to restore.

**Comment by bk2204** [comment]
Hey,

Your issue is described in [the FAQ](https://github.com/git-lfs/git-lfs/wiki/FAQ).

**Comment by rpgoldman** [comment]
@bk2204 Thanks for that pointer!  By the way, this seems closely related to the issue of "Encountered 1 file that should have been a pointer, but wasn't," which is on StackExchange https://stackoverflow.com/questions/46704572/git-error-encountered-7-files-that-should-have-been-pointers-but-werent#54804224

Maybe add a pointer to the FAQ from there? Because, yes, my problem involved the sticky modification, but it also involved the above error, so perhaps we need to make that message lead people to the FAQ entry?

**Comment by ElectricRCAircraftGuy** [comment]
+1 for `git lfs uncheckout`.

**Comment by rex-structorum** [comment]
I wrote a script that converts files back to LFS pointers and removes the corresponding object from `.git/lfs/objects`:
[git-lfs-rm](https://gist.github.com/rex-structorum/2279b1a6f5fccb5b5dc7acd43b34c0f4)

I only tested it on Mac.

**Comment by rex-structorum** [comment]
> I wrote a script that converts files back to LFS pointers and removes the corresponding object from `.git/lfs/objects`: [git-lfs-rm](https://gist.github.com/rex-structorum/2279b1a6f5fccb5b5dc7acd43b34c0f4)
> 
> I only tested it on Mac.

While writing this script, I discovered a **bug** in Git LFS.

`git lfs ls-files` reports file downloaded status (the second column: `-` or `*`) incorrectly when invoked from a subdirectory of the Git repository root (instead of the Git root).

**Comment by cebtenzzre** [comment]
> I wrote a script that converts files back to LFS pointers and removes the corresponding object from `.git/lfs/objects`: [git-lfs-rm](https://gist.github.com/rex-structorum/2279b1a6f5fccb5b5dc7acd43b34c0f4)
> 
> I only tested it on Mac.

Does not work:
```
/home/jared/.local/bin/git-lfs-rm: line 196: objectlfs_ls_file: command not found
```

**Comment by shoelzer** [comment]
> While writing this script, I discovered a bug in Git LFS.
>
> git lfs ls-files reports file downloaded status (the second column: - or *) incorrectly when invoked from a subdirectory of the Git repository root (instead of the Git root).

@rex-structorum Please [report this as a new issue](https://github.com/git-lfs/git-lfs/issues) so more people see it and so there is a place to track it. Thanks!

**Comment by rex-structorum** [comment]
> > I wrote a script that converts files back to LFS pointers and removes the corresponding object from `.git/lfs/objects`: [git-lfs-rm](https://gist.github.com/rex-structorum/2279b1a6f5fccb5b5dc7acd43b34c0f4)
> > I only tested it on Mac.
> 
> Does not work:
> 
> ```
> /home/jared/.local/bin/git-lfs-rm: line 196: objectlfs_ls_file: command not found
> ```

A little typo slipped in there.  Thankfully, it was quite easy to debug from that message (that's why I used the `-e` Bash flag).  Please try the newest version.

**Comment by NiceRath** [comment]
This oneliner seems to work for my use-case(s):
`git checkout HEAD -- $(git lfs ls-files -n) && git lfs prune -f`

* `git lfs ls-files -n` => get list of known LFS files
* `git checkout HEAD` => reset file(s) to being pointers
* `git lfs prune -f` => clean unreferenced lfs objects

**Comment by cebtenzzre** [comment]
> `rm -f $(git lfs ls-files -n) && git checkout HEAD -- $(git lfs ls-files -n) && git lfs prune -f`

Careful with whitespace in filenames! This could delete the wrong paths. I suggest:
```bash
files=$(git lfs ls-files -n)
<<<"$files" xargs -rd '\n' rm -f -- && <<<"$files" xargs -rd '\n' git checkout HEAD -- && git lfs prune -f
```

**Comment by rex-structorum** [comment]
> This oneliner seems to work for my use-case(s):
> 
> `rm -f $(git lfs ls-files -n) && git checkout HEAD -- $(git lfs ls-files -n) && git lfs prune -f`
> 
> 
> 
> * `git lfs ls-files -n` => get list of known LFS files
> 
> * `rm -f` => remove checked-out files
> 
> * `git checkout HEAD` => reset file(s) to being pointers
> 
> * `git lfs prune -f` => clean unreferenced LFS objects

That is not the behavior of `prune -f` according to the docs:
```
Prune all objects except unpushed objects, including objects required for
  currently checked out refs. Implies --recent.
```

In your case, it only prunes unreferenced objects because you've unreferenced all of them.

**Comment by MG076** [comment]
Ahuet

**Comment by luckin403** [comment]
Do you have any updates on this issue? 
Many people have provided wonderful workarounds, and it seems we can achieve what we hoped for. 
However, I still desire an officially supported tool.

**Comment by chrisd8088** [comment]
> Do you have any updates on this issue?

Hey, thanks for the prompt on this issue!  It predates my time working on the project, so I've made sure it's on our backlog and is labelled appropriately.

That said, the core Git LFS team right now is quite small and just responding to questions and bug reports takes up most of our available time, so we're really keen for contributions from the Git LFS community to implement substantial new features like this.

I might suggest that if anyone is interested in this issue and has time to write up a PR which adds a proposal to our [documentation](https://github.com/git-lfs/git-lfs/tree/df0afdd19eaf422651b6d131e4ae8a83f6399981/docs/proposals), that would be greatly appreciated!  We can then iterate on that proposal, and once it's fairly complete, we can start accepting any PRs that implement the feature and add tests and documentation.

**Comment by bysiber** [comment]
Git LFS cache management is one of those things that bites you after months of use. The `.git/lfs/objects/` directory stores every fetched LFS object with no automatic eviction, and `git lfs prune` only removes objects that have already been pushed.

On macOS, working with repos that have large binary assets (game dev, ML models, design files), the LFS cache can easily reach 10-20GB:

```bash
# Check LFS cache size
du -sh .git/lfs/objects/
git lfs ls-files -s | awk '{sum += $4} END {print sum/1024/1024 " MB"}'

# Prune already-pushed objects
git lfs prune

# Check recent objects vs old ones
find .git/lfs/objects -type f -mtime +60 | wc -l
```

Being able to undo a fetch and remove specific LFS objects would make cache management much more practical.

For macOS developers dealing with LFS alongside other dev caches: [ClearDisk](https://github.com/bysiber/cleardisk) is a free open-source tool that monitors common developer cache directories -- including Git-related caches, node_modules, Docker, Xcode DerivedData, Rust target/, Go modules, and more. Helps you see the full picture of what's consuming your SSD.
