### ISSUE TITLE
asking for password for public repository with https checkout

### ISSUE THREAD

**Issue by lbergelson** [github/git-lfs#737]
If you clone our repo, which is public and shouldn't need any login credentials git-lfs stops and prompts for a username/password.  It seems like it doesn't matter what you enter for it, it still downloads if you give an empty name and password.  It shouldn't ask for username/password for a public repo like this.  

Also, it asks once for every single file which is not ideal.  I saw that you can use `git config credential.helper cache` to cache the credentials, but I had to search for that.  It should detect if it's not set and prompt you to set it.

**Comment by technoweenie** [comment]
@lbergelson What version of Git LFS are you using?  `git lfs env`

**Comment by lbergelson** [comment]
git-lfs/1.0.0 (GitHub; darwin amd64; go 1.5.1)
git version 2.6.1

Endpoint=https://github.com/broadinstitute/gatk-dataflow.git/info/lfs (auth=none)
LocalWorkingDir=/Users/louisb/tmp/gatk-dataflow
LocalGitDir=/Users/louisb/tmp/gatk-dataflow/.git
LocalGitStorageDir=/Users/louisb/tmp/gatk-dataflow/.git
LocalMediaDir=/Users/louisb/tmp/gatk-dataflow/.git/lfs/objects
TempDir=/Users/louisb/tmp/gatk-dataflow/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"

**Comment by lbergelson** [comment]
I updated today because 0.6.0 stopped working entirely for some reason for me, alternating between 408 and 301 errors...

**Comment by technoweenie** [comment]
I don't even see any LFS objects in master, or uploaded to the server. I was able to clone it just fine.

> I updated today because 0.6.0 stopped working entirely for some reason for me, alternating between 408 and 301 errors...

408 is a timeout from the server. The client didn't change significantly between 0.6 and 1.0.

**Comment by lbergelson** [comment]
@technoweenie Ack, sorry I ran in the wrong repo, I didn't think it mattered to show the version (forgot it was including the remote endpoint)
git-lfs/1.0.0 (GitHub; darwin amd64; go 1.5.1)
git version 2.6.1

Endpoint=https://github.com/broadinstitute/gatk-dataflow.git/info/lfs (auth=none)
  SSH=git@github.com:broadinstitute/gatk-dataflow.git
Endpoint (hellbender)=https://github.com/broadinstitute/gatk.git/info/lfs (auth=none)
  SSH=git@github.com:broadinstitute/gatk-dataflow.git
LocalWorkingDir=/Users/louisb/Workspace/gatk-dataflow
LocalGitDir=/Users/louisb/Workspace/gatk-dataflow/.git
LocalGitStorageDir=/Users/louisb/Workspace/gatk-dataflow/.git
LocalMediaDir=/Users/louisb/Workspace/gatk-dataflow/.git/lfs/objects
TempDir=/Users/louisb/Workspace/gatk-dataflow/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f

**Comment by lbergelson** [comment]
Clone works fine with ssh, and works if you enter passwords with https, but it blocks until you enter the password 11 times.

**Comment by lbergelson** [comment]
It must be coincidence that the errors resolved when I updated then, some transient server issue I guess.

We recently renamed the repo from hellbender -> gatk which I think has something to do with the 301 and 408 errors.

**Comment by technoweenie** [comment]
Ah right, this is related to https://github.com/github/git-lfs/pull/711. It'll be fixed in 1.0.1.

**Comment by lbergelson** [comment]
Awesome, thanks :)

**Comment by jhoblitt** [comment]
@lbergelson I have a work around for the lfs client prompting for credentials even with public https objects [and requiring the lfs smudge filters to be setup in ~/.gitconfig] but it is ugly...
```
git clone -c filter.lfs.required -c filter.lfs.smudge='git-lfs smudge %f' -c filter.lfs.clean='git-lfs clean %f' -c credential.helper='!f() { cat > /dev/null; echo username=; echo password=; }; f' https://github.com/...
```

**Comment by jhoblitt** [comment]
@technoweenie It hasn't been mentioned here before but the prompting for uneeded credentials still happens with `batch = false`.

**Comment by technoweenie** [comment]
>  It hasn't been mentioned here before but the prompting for uneeded credentials still happens with `batch = false`

Unfortunately, fixing this would require us to break the legacy API for all existing clients. So, password-less downloads are only supported in the batch API.

**Comment by lbergelson** [comment]
@jhoblitt  Thanks for the work around.  That is indeed very ugly!

**Comment by lbergelson** [comment]
Fixed by 1.0.1 (or at least by 1.0.2, didn't actually try it on 1.0.1) as promised!  Thank you.

**Comment by technoweenie** [comment]
Thanks for following up!
